import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { KeyRound, PauseCircle, PlayCircle, RadioTower } from "lucide-react";
import { useState } from "react";
import { api } from "../api";
import { ErrorState, Loading, PageHeading, time } from "../components/Ui";

export function ConnectorOpsPage() {
  const client = useQueryClient(); const integrations = useQuery({ queryKey: ["integrations"], queryFn: api.integrations }); const [selected, setSelected] = useState<string>(); const [secret, setSecret] = useState<string>();
  const current = integrations.data?.find((item) => item.id === selected) ?? integrations.data?.[0]; const deliveries = useQuery({ queryKey: ["integration-deliveries", current?.id], queryFn: () => api.integrationDeliveries(current!.id), enabled: Boolean(current) });
  const setStatus = useMutation({ mutationFn: ({ id, status }: { id: string; status: "active" | "disabled" }) => api.setIntegrationStatus(id, status), onSuccess: () => client.invalidateQueries({ queryKey: ["integrations"] }) });
  const rotate = useMutation({ mutationFn: api.rotateIntegrationSecret, onSuccess: (result) => { setSecret(result.webhookSecret); client.invalidateQueries({ queryKey: ["integrations"] }); } });
  if (integrations.isLoading) return <Loading />; if (integrations.error) return <ErrorState error={integrations.error} />;
  return <><PageHeading eyebrow="Phase 16 / connector operations" title="Connector control room" copy="Human-controlled source lifecycle, signing-key rotation, and durable delivery evidence." />
    <div className="connector-layout"><section className="data-panel connector-list"><header><div><span className="panel-label">Connections</span><h2>Configured sources</h2></div></header>{integrations.data!.map((item) => <button className={current?.id === item.id ? "selected" : ""} onClick={() => setSelected(item.id)} key={item.id}><RadioTower size={15} /><div><b>{item.name}</b><small>{item.provider.replaceAll("_", " ")} · v{item.secretVersion}</small></div><span className={`connection connection--${item.status}`}>{item.status}</span></button>)}{!integrations.data!.length && <p className="empty-copy">Create a signed source from the Launchpad first.</p>}</section>
      <section className="data-panel connector-detail">{current ? <><header><div><span className="panel-label">Selected connector</span><h2>{current.name}</h2></div><span className={`connection connection--${current.status}`}>{current.status}</span></header><div className="connector-actions"><button className="button button--quiet" disabled={setStatus.isPending} onClick={() => setStatus.mutate({ id: current.id, status: current.status === "active" ? "disabled" : "active" })}>{current.status === "active" ? <PauseCircle size={14} /> : <PlayCircle size={14} />}{current.status === "active" ? " Disable source" : " Enable source"}</button><button className="button button--primary" disabled={rotate.isPending} onClick={() => rotate.mutate(current.id)}><KeyRound size={14} /> {rotate.isPending ? "Rotating" : "Rotate signing secret"}</button></div>{secret && <div className="notice"><b>New secret—save it now.</b><code>{secret}</code></div>}<h3 className="subhead">Delivery evidence / {deliveries.data?.length ?? 0}</h3>{deliveries.isLoading ? <Loading label="Reading delivery evidence" /> : deliveries.error ? <ErrorState error={deliveries.error} /> : <div className="delivery-list">{deliveries.data?.map((delivery) => <article key={delivery.id}><b>{time(delivery.receivedAt)}</b><span>{delivery.eventCount} events · {delivery.indicatorCount} indicators</span><small>{delivery.externalDeliveryId}</small></article>)}{!deliveries.data?.length && <p className="empty-copy">No signed deliveries have been stored for this connector.</p>}</div>}</> : <p className="empty-copy">Select a connector to inspect its controls and evidence.</p>}</section></div>
  </>;
}
