import { useMemo, useState, type FormEvent } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Activity, ArrowRight, BrainCircuit, Check, CircleDot, GitBranch, Network, Play, Plus, RadioTower, RefreshCw, ShieldCheck, Siren, Waypoints } from "lucide-react";
import type { Asset, Incident, IncidentStatus } from "@cascadia/contracts";
import { api } from "../api";
import { Empty, ErrorState, Loading, PageHeading, Severity, time } from "../components/Ui";

function useCoreData() {
  const assets = useQuery({ queryKey: ["assets"], queryFn: api.assets });
  const events = useQuery({ queryKey: ["events"], queryFn: api.events });
  const findings = useQuery({ queryKey: ["findings"], queryFn: api.findings });
  const incidents = useQuery({ queryKey: ["incidents"], queryFn: api.incidents });
  return { assets, events, findings, incidents };
}

export function OverviewPage() {
  const { assets, events, findings, incidents } = useCoreData();
  const boundaries = useQuery({ queryKey: ["boundaries"], queryFn: api.boundaries });
  const loading = [assets, events, findings, incidents].some((query) => query.isLoading);
  const error = [assets, events, findings, incidents].find((query) => query.error)?.error;
  if (loading) return <Loading />; if (error) return <ErrorState error={error} />;
  const open = incidents.data!.filter((item) => !["resolved", "closed"].includes(item.status));
  const critical = findings.data!.filter((item) => item.level === "critical" && item.disposition !== "dismissed");
  const maxCount = Math.max(1, ...["low", "medium", "high", "critical"].map((level) => events.data!.filter((event) => event.severity === level).length));
  return <><PageHeading eyebrow="Live operational picture" title="Resilience overview" copy="A real-time view built only from telemetry and decisions stored by your organization." />
    <section className="metric-grid"><Metric label="Monitored assets" value={assets.data!.length} meta="Inventory records" icon={Network} /><Metric label="Stored events" value={events.data!.length} meta="Normalized telemetry" icon={Activity} /><Metric label="Open incidents" value={open.length} meta={open.some((item) => item.priority === "p1") ? "P1 attention required" : "No open P1 cases"} icon={Siren} tone={open.some((item) => item.priority === "p1") ? "red" : undefined} /><Metric label="Critical findings" value={critical.length} meta="Awaiting human review" icon={BrainCircuit} tone={critical.length ? "amber" : undefined} /></section>
    <div className="dashboard-grid"><section className="data-panel span-2"><header><div><span className="panel-label">Signal distribution</span><h2>Telemetry severity</h2></div><span className="live-label"><i /> Live database</span></header><div className="bar-chart">{["low", "medium", "high", "critical"].map((level) => { const count = events.data!.filter((event) => event.severity === level).length; return <div className="bar-column" key={level}><div className="bar-track"><i className={`bar bar--${level}`} style={{ height: `${Math.max(count ? 8 : 1, count / maxCount * 100)}%` }}><b>{count}</b></i></div><span>{level}</span></div>; })}</div></section>
      <section className="data-panel"><header><div><span className="panel-label">Safety boundary</span><h2>Control state</h2></div><ShieldCheck size={18} /></header>{boundaries.data ? <div className="boundary-list"><p><Check size={13} /> Autonomous execution disabled</p><p><Check size={13} /> ML review required</p><p><Check size={13} /> Recommendations need approval</p><p><Check size={13} /> Source content treated as evidence</p></div> : <Loading label="Reading boundaries" />}</section>
      <section className="data-panel span-3"><header><div><span className="panel-label">Incident command</span><h2>Recent cases</h2></div><a href="/app/incidents">Open incident desk <ArrowRight size={13} /></a></header>{incidents.data!.length ? <div className="incident-strip">{incidents.data!.slice(0,4).map((incident) => <article key={incident.id}><span className="reference">{incident.reference}</span><Severity value={incident.severity} /><h3>{incident.title}</h3><p>{incident.status.replaceAll("_", " ")} · updated {time(incident.updatedAt)}</p></article>)}</div> : <Empty title="No incidents recorded" copy="Cases appear here only after an operator confirms and creates them." />}</section>
    </div></>;
}

function Metric({ label, value, meta, icon: Icon, tone }: { label: string; value: number; meta: string; icon: typeof Activity; tone?: "red" | "amber" }) { return <article className={`metric-card ${tone ? `metric-card--${tone}` : ""}`}><div><span>{label}</span><Icon size={16} /></div><strong>{String(value).padStart(2, "0")}</strong><p>{meta}</p></article>; }

function AssetMap({ assets }: { assets: Asset[] }) {
  const points = assets.slice(0, 18).map((asset, index) => ({ asset, x: 13 + (index * 37) % 78, y: 18 + (index * 53) % 66 }));
  return <div className="asset-map">{points.length > 1 && <svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true">{points.slice(1).map((point, index) => <line key={point.asset.id} x1={points[index]!.x} y1={points[index]!.y} x2={point.x} y2={point.y} />)}</svg>}{points.map(({ asset, x, y }) => <button key={asset.id} className={`map-node map-node--${asset.criticality}`} style={{ left: `${x}%`, top: `${y}%` }} title={`${asset.name} — ${asset.criticality}`}><i /><span>{asset.name}</span></button>)}{!points.length && <Empty title="Topology is empty" copy="Add real assets through the API or inventory import to populate this view." />}</div>;
}

export function AssetsPage() {
  const assets = useQuery({ queryKey: ["assets"], queryFn: api.assets }); const dependencies = useQuery({ queryKey: ["dependencies"], queryFn: api.dependencies }); const vulnerabilities = useQuery({ queryKey: ["vulnerabilities"], queryFn: api.vulnerabilities }); const services = useQuery({ queryKey: ["services"], queryFn: api.services });
  if ([assets, dependencies, vulnerabilities, services].some((q) => q.isLoading)) return <Loading />; const error = [assets, dependencies, vulnerabilities, services].find((q) => q.error)?.error; if (error) return <ErrorState error={error} />;
  return <><PageHeading eyebrow="Operational topology" title="Assets & dependencies" copy="The real inventory and service graph used by Cascadia's risk analysis." /><div className="submetrics"><span><b>{assets.data!.length}</b> assets</span><span><b>{dependencies.data!.length}</b> dependencies</span><span><b>{services.data!.length}</b> critical services</span><span><b>{vulnerabilities.data!.length}</b> vulnerabilities</span></div><section className="data-panel map-panel"><header><div><span className="panel-label">Live topology</span><h2>Infrastructure plane</h2></div><Waypoints size={18} /></header><AssetMap assets={assets.data!} /></section><section className="data-panel table-panel"><header><div><span className="panel-label">Inventory</span><h2>Monitored assets</h2></div></header>{assets.data!.length ? <div className="table-wrap"><table><thead><tr><th>Asset</th><th>Type</th><th>Criticality</th><th>Classification</th><th>External ID</th></tr></thead><tbody>{assets.data!.map((asset) => <tr key={asset.id}><td><b>{asset.name}</b>{asset.hostname && <small>{asset.hostname}</small>}</td><td>{asset.assetType}</td><td><Severity value={asset.criticality} /></td><td>{asset.classification}</td><td className="mono">{asset.externalId}</td></tr>)}</tbody></table></div> : <Empty title="No assets stored" copy="Import a CMDB, CycloneDX inventory, or create an asset through the API." />}</section></>;
}

export function DetectionPage() {
  const client = useQueryClient(); const findings = useQuery({ queryKey: ["findings"], queryFn: api.findings }); const models = useQuery({ queryKey: ["models"], queryFn: api.models });
  const review = useMutation({ mutationFn: ({ id, disposition }: { id: string; disposition: "acknowledged" | "dismissed" | "escalated" }) => api.reviewFinding(id, { disposition, comment: `Disposition recorded from the Phase 8 analyst console: ${disposition}.` }), onSuccess: () => client.invalidateQueries({ queryKey: ["findings"] }) });
  const evaluate = useMutation({ mutationFn: api.evaluate, onSuccess: () => client.invalidateQueries({ queryKey: ["findings"] }) });
  if (findings.isLoading || models.isLoading) return <Loading />; if (findings.error || models.error) return <ErrorState error={findings.error ?? models.error} />;
  const active = models.data!.find((model) => model.status === "active");
  return <><PageHeading eyebrow="Explainable ML" title="Detection review" copy="Every score is evidence for an analyst—not authorization to act." action={<button className="button button--quiet" onClick={() => evaluate.mutate()} disabled={evaluate.isPending}><Play size={14} /> {evaluate.isPending ? "Evaluating" : "Evaluate new telemetry"}</button>} /><section className="model-band"><div><span>Active model</span><b>{active ? `v${active.version} / ${active.algorithm}` : "No trained model"}</b></div><div><span>Finding threshold</span><b>{active ? active.findingThreshold : "—"}</b></div><div><span>Autonomous response</span><b className="safe">Disabled</b></div></section>{evaluate.data && <div className="notice">Evaluated {evaluate.data.eventsEvaluated} events · created {evaluate.data.findingsCreated} findings{evaluate.data.noOp ? " · no new data" : ""}</div>}<div className="finding-grid">{findings.data!.map((finding) => <article className="finding-card" key={finding.id}><header><Severity value={finding.level} /><span>{finding.anomalyScore}/100</span></header><h2>{finding.factors.sort((a,b) => b.score-a.score)[0]?.name.replaceAll("_", " ")}</h2><p>Event <span className="mono">{finding.eventId.slice(0,8)}</span> · {time(finding.createdAt)}</p><div className="factor-list">{finding.factors.map((factor) => <div key={factor.name}><span>{factor.name.replaceAll("_", " ")}</span><i><b style={{ width: `${factor.score}%` }} /></i><strong>{factor.score}</strong></div>)}</div><footer><span className={`disposition disposition--${finding.disposition}`}>{finding.disposition}</span>{finding.disposition === "new" && <div><button onClick={() => review.mutate({ id: finding.id, disposition: "acknowledged" })}>Acknowledge</button><button onClick={() => review.mutate({ id: finding.id, disposition: "escalated" })}>Escalate</button><button onClick={() => review.mutate({ id: finding.id, disposition: "dismissed" })}>Dismiss</button></div>}</footer></article>)}{!findings.data!.length && <Empty title="No anomaly findings" copy="Train a model and manually evaluate newly stored telemetry to create explainable findings." />}</div></>;
}

const transitions: Record<IncidentStatus, IncidentStatus[]> = { new: ["triaged"], triaged: ["investigating"], investigating: ["contained", "resolved"], contained: ["recovering", "resolved"], recovering: ["resolved"], resolved: ["closed", "investigating"], closed: ["investigating"] };
export function IncidentsPage() {
  const client = useQueryClient(); const incidents = useQuery({ queryKey: ["incidents"], queryFn: api.incidents }); const [selectedId, setSelectedId] = useState<string>(); const [createOpen, setCreateOpen] = useState(false); const [candidates, setCandidates] = useState<Awaited<ReturnType<typeof api.correlate>>["candidates"]>([]);
  const correlate = useMutation({ mutationFn: () => api.correlate(), onSuccess: (result) => setCandidates(result.candidates) });
  const transition = useMutation({ mutationFn: ({ incident, status }: { incident: Incident; status: IncidentStatus }) => api.transitionIncident(incident.id, { status, comment: `Status changed to ${status} from the Phase 8 incident desk.`, ...(["resolved", "closed"].includes(status) ? { resolutionSummary: "Resolution confirmed by an authorized operator through the incident desk." } : {}) }), onSuccess: () => client.invalidateQueries({ queryKey: ["incidents"] }) });
  if (incidents.isLoading) return <Loading />; if (incidents.error) return <ErrorState error={incidents.error} />; const selected = incidents.data!.find((item) => item.id === selectedId) ?? incidents.data![0];
  return <><PageHeading eyebrow="Incident command" title="Incident operations" copy="Durable cases, evidence, ownership, SLAs, and controlled lifecycle changes." action={<div className="heading-actions"><button className="button button--quiet" onClick={() => correlate.mutate()}><CircleDot size={14} /> Correlate signals</button><button className="button button--primary" onClick={() => setCreateOpen(true)}><Plus size={14} /> New incident</button></div>} />{candidates.length > 0 && <section className="candidate-band"><header><b>Analyst confirmation required</b><span>{candidates.length} candidate{candidates.length === 1 ? "" : "s"}; none created automatically</span></header>{candidates.map((candidate) => <article key={candidate.id}><Severity value={candidate.recommendedSeverity} /><div><b>{candidate.title}</b><p>{candidate.rationale}</p></div></article>)}</section>}
    <div className="incident-desk"><section className="incident-list data-panel">{incidents.data!.map((incident) => <button className={selected?.id === incident.id ? "selected" : ""} onClick={() => setSelectedId(incident.id)} key={incident.id}><span className="reference">{incident.reference}</span><Severity value={incident.severity} /><b>{incident.title}</b><small>{incident.status} · {incident.priority.toUpperCase()}</small></button>)}{!incidents.data!.length && <Empty title="No incidents" copy="Create a case manually or review correlation candidates first." />}</section>
      <section className="incident-detail data-panel">{selected ? <><header><div><span className="reference">{selected.reference}</span><h2>{selected.title}</h2></div><Severity value={selected.severity} /></header><p>{selected.summary}</p><div className="incident-facts"><span><small>Status</small><b>{selected.status}</b></span><span><small>Priority</small><b>{selected.priority.toUpperCase()}</b></span><span><small>Acknowledge by</small><b>{time(selected.acknowledgementDueAt)}</b></span><span><small>Resolve by</small><b>{time(selected.resolutionDueAt)}</b></span></div><div className="transition-row">{transitions[selected.status].map((status) => <button key={status} onClick={() => transition.mutate({ incident: selected, status })}>Move to {status.replaceAll("_", " ")} <ArrowRight size={13} /></button>)}</div><h3 className="subhead">Timeline / {selected.timeline.length}</h3><div className="timeline">{selected.timeline.toReversed().map((entry) => <article key={entry.id}><i /><div><b>{entry.type.replaceAll("_", " ")}</b><p>{entry.message}</p><small>{time(entry.occurredAt)}</small></div></article>)}</div></> : <Empty title="Select an incident" copy="Choose a case to review its evidence and timeline." />}</section></div>{createOpen && <CreateIncident close={() => setCreateOpen(false)} />}</>;
}

function CreateIncident({ close }: { close: () => void }) {
  const client = useQueryClient(); const create = useMutation({ mutationFn: api.createIncident, onSuccess: () => { client.invalidateQueries({ queryKey: ["incidents"] }); close(); } });
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); create.mutate({ idempotencyKey: crypto.randomUUID(), title: String(data.get("title")), summary: String(data.get("summary")), severity: String(data.get("severity")) as "low"|"medium"|"high"|"critical", priority: String(data.get("priority")) as "p1"|"p2"|"p3"|"p4", tags: [], evidence: [] }); };
  return <div className="modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) close(); }}><form className="modal" onSubmit={submit}><p className="eyebrow">Human-created case</p><h2>Create incident</h2><label>Title<input name="title" minLength={3} required /></label><label>Summary<textarea name="summary" rows={4} required /></label><div className="form-row"><label>Severity<select name="severity" defaultValue="high"><option>low</option><option>medium</option><option>high</option><option>critical</option></select></label><label>Priority<select name="priority" defaultValue="p2"><option>p1</option><option>p2</option><option>p3</option><option>p4</option></select></label></div>{create.error && <ErrorState error={create.error} />}<div className="modal-actions"><button type="button" onClick={close}>Cancel</button><button className="button button--primary" type="submit" disabled={create.isPending}>Create durable case</button></div></form></div>;
}

export function RiskPage() {
  const client = useQueryClient(); const analyses = useQuery({ queryKey: ["analyses"], queryFn: api.analyses }); const assets = useQuery({ queryKey: ["assets"], queryFn: api.assets }); const [entries, setEntries] = useState<string[]>([]);
  const analyze = useMutation({ mutationFn: () => api.analyze(entries), onSuccess: () => client.invalidateQueries({ queryKey: ["analyses"] }) }); if (analyses.isLoading || assets.isLoading) return <Loading />; if (analyses.error || assets.error) return <ErrorState error={analyses.error ?? assets.error} />; const latest = analyses.data![0];
  return <><PageHeading eyebrow="Consequence intelligence" title="Attack-path analysis" copy="Explainable paths through the stored operational topology—never inferred from simulated assets." action={<button className="button button--primary" disabled={!entries.length || analyze.isPending} onClick={() => analyze.mutate()}><GitBranch size={14} /> Analyze selected entries</button>} /><section className="entry-selector data-panel"><header><div><span className="panel-label">Entry assets</span><h2>Select observed footholds</h2></div><span>{entries.length} selected</span></header><div>{assets.data!.map((asset) => <label key={asset.id}><input type="checkbox" checked={entries.includes(asset.id)} onChange={(event) => setEntries(event.target.checked ? [...entries, asset.id] : entries.filter((id) => id !== asset.id))} /><span>{asset.name}</span><Severity value={asset.criticality} /></label>)}</div></section>{latest ? <div className="risk-layout"><section className="data-panel risk-summary"><header><div><span className="panel-label">Latest analysis</span><h2>Blast radius</h2></div><span>{time(latest.generatedAt)}</span></header><strong>{latest.blastRadius.reachableAssetIds.length}</strong><p>reachable assets across {latest.paths.length} identified paths</p><div className="risk-counts">{Object.entries(latest.blastRadius.assetsByCriticality).map(([key,value]) => <span key={key}><b>{value}</b>{key}</span>)}</div></section><section className="data-panel path-list"><header><div><span className="panel-label">Ranked paths</span><h2>Exposure routes</h2></div></header>{latest.paths.map((path,index) => <article key={index}><span>{String(index+1).padStart(2,"0")}</span><div><b>{path.assetIds.length} assets / {path.dependencyIds.length} hops</b><p>{path.factors.map((factor) => factor.explanation).join(" ")}</p></div><strong>{path.riskScore}</strong><Severity value={path.riskLevel} /></article>)}{!latest.paths.length && <Empty title="No reachable path" copy="The selected entry assets do not reach a modeled critical service." />}</section></div> : <Empty title="No stored analysis" copy="Select one or more real inventory assets and run the first attack-path analysis." />}</>;
}

export function ResponsesPage() { const responses = useQuery({ queryKey: ["responses"], queryFn: api.responses }); if (responses.isLoading) return <Loading />; if (responses.error) return <ErrorState error={responses.error} />; return <><PageHeading eyebrow="Human approval plane" title="Response decisions" copy="Compare security benefit, operational impact, rollback readiness, and approval evidence." /><div className="response-grid">{responses.data!.map((scenario) => <article className="response-card" key={scenario.id}><header><span className={`disposition disposition--${scenario.status}`}>{scenario.status.replaceAll("_", " ")}</span><span>{time(scenario.generatedAt)}</span></header><h2>{scenario.options.length} modeled options</h2><p>Incident <span className="mono">{scenario.incidentId.slice(0,8)}</span> · execution authorized: <b>{String(scenario.executionAuthorized)}</b></p>{scenario.options.slice().sort((a,b)=>a.residualRiskScore-b.residualRiskScore).map((option) => <div className="response-option" key={option.id}><div><b>{option.title}</b><small>{option.actionType.replaceAll("_", " ")}</small></div><span>Benefit <b>{option.securityBenefit}</b></span><span>Impact <b>{option.operationalImpact}</b></span><span>Residual <b>{option.residualRiskScore}</b></span></div>)}</article>)}{!responses.data!.length && <Empty title="No response scenarios" copy="Scenarios appear only after an operator simulates policy-governed response candidates." />}</div></>;
}

export function IntegrationsPage() {
  const client = useQueryClient(); const integrations = useQuery({ queryKey: ["integrations"], queryFn: api.integrations }); const sources = useQuery({ queryKey: ["taxii"], queryFn: api.taxiiSources }); const indicators = useQuery({ queryKey: ["indicators"], queryFn: api.indicators }); const sync = useMutation({ mutationFn: api.syncTaxii, onSuccess: () => { client.invalidateQueries({ queryKey: ["taxii"] }); client.invalidateQueries({ queryKey: ["indicators"] }); } });
  if ([integrations,sources,indicators].some((q)=>q.isLoading)) return <Loading />; const error=[integrations,sources,indicators].find((q)=>q.error)?.error;if(error)return <ErrorState error={error}/>;
  return <><PageHeading eyebrow="Live data plane" title="Integrations" copy="Signed delivery intake and operator-controlled TAXII synchronization. Source content always remains untrusted data." /><section className="integration-grid">{integrations.data!.map((integration)=><article className="integration-card" key={integration.id}><header><RadioTower size={17}/><span className={`connection connection--${integration.status}`}>{integration.status}</span></header><h2>{integration.name}</h2><p>{integration.provider.replaceAll("_"," ")} / {integration.dataType.replaceAll("_"," ")}</p><dl><div><dt>Secret version</dt><dd>v{integration.secretVersion}</dd></div><div><dt>Last delivery</dt><dd>{integration.lastDeliveryAt?time(integration.lastDeliveryAt):"Never"}</dd></div></dl></article>)}{!integrations.data!.length&&<Empty title="No integrations configured" copy="Organization administrators can add signed SIEM, EDR, or TAXII connections through the API."/>}</section><section className="data-panel table-panel"><header><div><span className="panel-label">Threat intelligence</span><h2>TAXII sources / {indicators.data!.length} indicators</h2></div></header>{sources.data!.length?<div className="source-list">{sources.data!.map((source)=><article key={source.id}><div><b>{source.name}</b><small>{source.apiRootUrl} · collection {source.collectionId}</small></div><span className={`connection connection--${source.status}`}>{source.status}</span><span>Last sync {source.lastSyncAt?time(source.lastSyncAt):"never"}</span><button disabled={sync.isPending||source.status!=="active"} onClick={()=>sync.mutate(source.id)}><RefreshCw size={13}/> Sync now</button></article>)}</div>:<Empty title="No TAXII sources" copy="Configure a TAXII 2.1 collection to pull real threat intelligence manually."/>}</section></>;
}
