import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { type FormEvent, useState } from "react";
import { Boxes, FileBadge } from "lucide-react";
import { api } from "../api";
import { ErrorState, Loading, PageHeading } from "../components/Ui";

export function EnrichmentPage() {
  const client = useQueryClient(); const assets = useQuery({ queryKey: ["assets"], queryFn: api.assets }); const [selected, setSelected] = useState<string>(); const save = useMutation({ mutationFn: ({ id, input }: { id: string; input: unknown }) => api.enrichAsset(id, input), onSuccess: () => client.invalidateQueries({ queryKey: ["assets"] }) });
  if (assets.isLoading) return <Loading />; if (assets.error) return <ErrorState error={assets.error} />;
  const asset = assets.data!.find((item) => item.id === selected) ?? assets.data![0]; const existing = asset?.metadata.sbom as { format?: string; componentCount?: number; sourceUrl?: string; generatedAt?: string } | undefined;
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!asset) return; const data = new FormData(event.currentTarget); const sourceUrl = String(data.get("sourceUrl") ?? "").trim(); const generatedAt = String(data.get("generatedAt") ?? "").trim(); save.mutate({ id: asset.id, input: { lifecycle: String(data.get("lifecycle")), ownerTeam: String(data.get("ownerTeam") ?? "").trim() || undefined, sbom: { format: String(data.get("format")), componentCount: Number(data.get("componentCount")), ...(sourceUrl ? { sourceUrl } : {}), ...(generatedAt ? { generatedAt: new Date(generatedAt).toISOString() } : {}) } } }); };
  return <><PageHeading eyebrow="Phase 27 / asset enrichment" title="Asset intelligence" copy="Attach lifecycle, owner team, and SBOM evidence to a real stored asset. This information feeds analyst context without fabricating components." />
    <div className="enrichment-layout"><section className="data-panel enrichment-list"><header><div><span className="panel-label">Assets</span><h2>Choose record</h2></div><Boxes size={17} /></header>{assets.data!.map((item) => <button key={item.id} className={asset?.id === item.id ? "selected" : ""} onClick={() => setSelected(item.id)}><b>{item.name}</b><span>{String(item.metadata.lifecycle ?? "not enriched")}</span></button>)}</section>{asset ? <form className="data-panel" onSubmit={submit}><header><div><span className="panel-label">{asset.externalId}</span><h2>{asset.name}</h2></div><FileBadge size={18} /></header><div className="config-body"><label>Lifecycle<select name="lifecycle" defaultValue={String(asset.metadata.lifecycle ?? "active")}><option>planned</option><option>active</option><option>maintenance</option><option>retired</option></select></label><label>Owner team<input name="ownerTeam" defaultValue={typeof asset.metadata.ownerTeam === "string" ? asset.metadata.ownerTeam : ""} placeholder="Infrastructure operations" /></label><div className="form-row"><label>SBOM format<select name="format" defaultValue={existing?.format ?? "cyclonedx"}><option>cyclonedx</option><option>spdx</option><option>other</option></select></label><label>Component count<input name="componentCount" type="number" min="0" defaultValue={existing?.componentCount ?? 0} required /></label></div><label>SBOM evidence URL (optional)<input name="sourceUrl" type="url" defaultValue={existing?.sourceUrl ?? ""} placeholder="https://…" /></label><label>SBOM generated at (optional)<input name="generatedAt" type="datetime-local" /></label>{save.error && <ErrorState error={save.error} />}<button className="button button--primary" disabled={save.isPending}>{save.isPending ? "Saving" : "Store enrichment"}</button></div></form> : <ErrorState error={new Error("Create an asset before adding enrichment.")} />}</div>
  </>;
}
