import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Filter, LockKeyhole, Search } from "lucide-react";
import { useMemo, useState } from "react";
import { api } from "../api";
import { ErrorState, Loading, PageHeading, time } from "../components/Ui";

export function EvidencePage() {
  const client = useQueryClient(); const events = useQuery({ queryKey: ["audit-events"], queryFn: api.auditEvents }); const anchors = useQuery({ queryKey: ["audit-anchors"], queryFn: api.auditAnchors }); const run = useMutation({ mutationFn: api.runAuditAnchor, onSuccess: () => { void client.invalidateQueries({ queryKey: ["audit-anchors"] }); void client.invalidateQueries({ queryKey: ["audit-events"] }); } }); const [search, setSearch] = useState(""); const [type, setType] = useState("all"); const [verified, setVerified] = useState<Record<number, boolean>>({});
  const types = useMemo(() => [...new Set(events.data?.map((event) => event.eventType) ?? [])].sort(), [events.data]);
  const visible = useMemo(() => (events.data ?? []).filter((event) => (type === "all" || event.eventType === type) && `${event.eventType} ${event.resourceType} ${event.resourceId}`.toLowerCase().includes(search.toLowerCase())), [events.data, search, type]);
  if (events.isLoading) return <Loading label="Reading append-only evidence" />; if (events.error) return <ErrorState error={events.error} />;
  return <><PageHeading eyebrow="Phase 15 / evidence explorer" title="Audit evidence" copy="A read-only, tenant-scoped record of durable actions. Viewing evidence never creates new audit activity." action={<button className="button button--primary" disabled={run.isPending} onClick={() => run.mutate()}>Anchor audit batch</button>} />
    <section className="data-panel mst-integrity"><header><div><span className="panel-label">MST Testnet integrity</span><h2>Audit Integrity</h2></div></header>{anchors.isLoading ? <p>Reading anchors…</p> : anchors.error ? <p>MST anchoring is not configured.</p> : anchors.data!.map((anchor) => <article className="mst-integrity-row" key={anchor.id}><div className="mst-integrity-summary"><b>{anchor.eventCount} events</b><span>{time(anchor.batchStartTime)} – {time(anchor.batchEndTime)} <em>{anchor.anchorStatus}</em></span></div><div className="mst-integrity-actions">{anchor.mstscanUrl && <a className="button button--quiet" href={anchor.mstscanUrl} target="_blank" rel="noreferrer">Open MSTScan</a>}<button className="button button--quiet" onClick={async () => { const result = await api.verifyAuditAnchor(anchor.id); setVerified((current) => ({ ...current, [anchor.id]: result.match })); }}>Verify batch</button>{verified[anchor.id] !== undefined && <strong className={verified[anchor.id] ? "verified" : "mismatch"}>{verified[anchor.id] ? "Verified" : "Mismatch"}</strong>}</div></article>)}{!anchors.isLoading && !anchors.data?.length && <p className="empty-copy">No audit batches have been anchored.</p>}</section>
    <section className="evidence-toolbar data-panel"><div><Search size={15} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search action or resource" /></div><label><Filter size={14} /><select value={type} onChange={(event) => setType(event.target.value)}><option value="all">All actions</option>{types.map((entry) => <option key={entry} value={entry}>{entry}</option>)}</select></label><span><LockKeyhole size={14} /> Append-only / {visible.length} shown</span></section>
    <section className="data-panel evidence-list"><header><div><span className="panel-label">IST record</span><h2>Operational history</h2></div></header>{visible.map((event) => <article key={event.id}><time>{time(event.occurredAt)}</time><div><b>{event.eventType.replaceAll(".", " / ").replaceAll("_", " ")}</b><p>{event.resourceType} · <span className="mono">{event.resourceId}</span>{event.actorUserId ? ` · actor ${event.actorUserId.slice(0, 8)}` : " · system-originated"}</p></div><span>{Object.keys(event.metadata).length ? `${Object.keys(event.metadata).length} evidence fields` : "No metadata"}</span></article>)}{!visible.length && <p className="empty-copy">No matching audit evidence is stored for this organization.</p>}</section>
  </>;
}
