import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CheckCircle2, DatabaseZap, PlugZap, Plus, ShieldCheck } from "lucide-react";
import { type FormEvent, useState } from "react";
import { api } from "../api";
import { ErrorState, Loading, PageHeading } from "../components/Ui";

export function LaunchpadPage() {
  const client = useQueryClient(); const assets = useQuery({ queryKey: ["assets"], queryFn: api.assets }); const integrations = useQuery({ queryKey: ["integrations"], queryFn: api.integrations });
  const [assetOpen, setAssetOpen] = useState(false); const [integrationOpen, setIntegrationOpen] = useState(false); const [webhookSecret, setWebhookSecret] = useState<string>();
  const createAsset = useMutation({ mutationFn: api.createAsset, onSuccess: () => { client.invalidateQueries({ queryKey: ["assets"] }); setAssetOpen(false); } });
  const createIntegration = useMutation({ mutationFn: api.createIntegration, onSuccess: (result) => { client.invalidateQueries({ queryKey: ["integrations"] }); setWebhookSecret(result.webhookSecret); setIntegrationOpen(false); } });
  if (assets.isLoading || integrations.isLoading) return <Loading />; if (assets.error || integrations.error) return <ErrorState error={assets.error ?? integrations.error} />;
  const steps = [{ done: assets.data!.length > 0, label: "Record real operational assets", copy: "Assets and dependencies form the topology used by risk analysis." }, { done: integrations.data!.some((item) => item.status === "active"), label: "Connect a signed telemetry source", copy: "Use the generated webhook secret only in your SIEM or EDR connector." }, { done: false, label: "Ingest and review evidence", copy: "After data arrives, train detection and let an analyst review findings." }];
  const submitAsset = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const latitudeRaw = String(data.get("latitude") ?? "").trim(); const longitudeRaw = String(data.get("longitude") ?? "").trim(); const latitude = Number(latitudeRaw); const longitude = Number(longitudeRaw); const siteName = String(data.get("siteName") ?? "").trim(); const metadata: Record<string, unknown> = {}; if (latitudeRaw && longitudeRaw && Number.isFinite(latitude) && Number.isFinite(longitude) && latitude >= -90 && latitude <= 90 && longitude >= -180 && longitude <= 180) { metadata.latitude = latitude; metadata.longitude = longitude; if (siteName) metadata.siteName = siteName; } createAsset.mutate({ externalId: String(data.get("externalId")), name: String(data.get("name")), assetType: String(data.get("assetType")), criticality: String(data.get("criticality")), classification: String(data.get("classification")), metadata }); };
  const submitIntegration = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); createIntegration.mutate({ name: String(data.get("name")), provider: String(data.get("provider")), dataType: "security_events", eventSource: String(data.get("eventSource")) }); };
  return <><PageHeading eyebrow="Phase 14 / guided setup" title="Operational launchpad" copy="Connect real data deliberately. Cascadia never creates telemetry, incidents, or response actions on its own." />
    <section className="launch-steps data-panel"><header><div><span className="panel-label">Readiness sequence</span><h2>From inventory to analyst review</h2></div></header>{steps.map((step, index) => <article key={step.label}><span>{step.done ? <CheckCircle2 size={17} /> : String(index + 1).padStart(2, "0")}</span><div><b>{step.label}</b><p>{step.copy}</p></div>{index === 0 && <button className="button button--quiet" onClick={() => setAssetOpen(true)}><Plus size={14} /> Add asset</button>}{index === 1 && <button className="button button--quiet" onClick={() => setIntegrationOpen(true)}><PlugZap size={14} /> Connect source</button>}</article>)}</section>
    <section className="setup-facts"><article><DatabaseZap size={18} /><b>{assets.data!.length}</b><span>stored assets</span></article><article><PlugZap size={18} /><b>{integrations.data!.filter((item) => item.status === "active").length}</b><span>active integrations</span></article><article><ShieldCheck size={18} /><b>0</b><span>autonomous actions</span></article></section>
    {webhookSecret && <section className="notice"><b>Save this webhook secret now.</b>&nbsp; It is shown only at creation. Configure it in the source system; never paste it into browser code.<code>{webhookSecret}</code></section>}
    {assetOpen && <div className="modal-backdrop"><form className="modal" onSubmit={submitAsset}><p className="eyebrow">Real inventory record</p><h2>Add asset</h2><label>Name<input name="name" required minLength={2} /></label><label>External ID<input name="externalId" required minLength={1} /></label><div className="form-row"><label>Type<select name="assetType" defaultValue="endpoint"><option>endpoint</option><option>server</option><option>network</option><option>database</option><option>medical_device</option><option>plc</option><option>rtu</option><option>iot</option><option>cloud_service</option><option>identity</option><option>other</option></select></label><label>Criticality<select name="criticality" defaultValue="medium"><option>low</option><option>medium</option><option>high</option><option>critical</option></select></label></div><label>Classification<select name="classification" defaultValue="confidential"><option>public</option><option>internal</option><option>confidential</option><option>restricted</option></select></label><label>Site name (optional)<input name="siteName" /></label><div className="form-row"><label>Latitude (optional)<input name="latitude" type="number" min="-90" max="90" step="any" /></label><label>Longitude (optional)<input name="longitude" type="number" min="-180" max="180" step="any" /></label></div>{createAsset.error && <ErrorState error={createAsset.error} />}<div className="modal-actions"><button type="button" onClick={() => setAssetOpen(false)}>Cancel</button><button className="button button--primary" disabled={createAsset.isPending}>Store asset</button></div></form></div>}
    {integrationOpen && <div className="modal-backdrop"><form className="modal" onSubmit={submitIntegration}><p className="eyebrow">Signed source intake</p><h2>Connect telemetry</h2><label>Connection name<input name="name" required minLength={2} placeholder="Production EDR webhook" /></label><div className="form-row"><label>Provider<select name="provider" defaultValue="microsoft_defender"><option>generic_webhook</option><option>splunk</option><option>microsoft_sentinel</option><option>elastic_security</option><option>crowdstrike</option><option>microsoft_defender</option></select></label><label>Source type<select name="eventSource" defaultValue="edr"><option>edr</option><option>siem</option></select></label></div>{createIntegration.error && <ErrorState error={createIntegration.error} />}<div className="modal-actions"><button type="button" onClick={() => setIntegrationOpen(false)}>Cancel</button><button className="button button--primary" disabled={createIntegration.isPending}>Create signed endpoint</button></div></form></div>}
  </>;
}
