import { useQuery } from "@tanstack/react-query";
import { ClipboardCheck, FlaskConical, ShieldCheck, TimerReset } from "lucide-react";
import { api } from "../api";
import { ErrorState, Loading, PageHeading, time } from "../components/Ui";

export function ResilienceReadinessPage() {
  const services = useQuery({ queryKey: ["services"], queryFn: api.services }); const policies = useQuery({ queryKey: ["response-policies"], queryFn: api.responsePolicies }); const scenarios = useQuery({ queryKey: ["responses"], queryFn: api.responses }); const incidents = useQuery({ queryKey: ["incidents"], queryFn: api.incidents });
  if ([services, policies, scenarios, incidents].some((query) => query.isLoading)) return <Loading label="Reading resilience evidence" />; const error = services.error ?? policies.error ?? scenarios.error ?? incidents.error; if (error) return <ErrorState error={error} />;
  const exercised = scenarios.data!; const unresolved = incidents.data!.filter((item) => !["resolved", "closed"].includes(item.status));
  return <><PageHeading eyebrow="Phase 35 / resilience exercise readiness" title="BCP / DR evidence board" copy="Readiness is calculated from stored services, response policies, human-run simulations, and incident workflow—not from assumed drill success." />
    <section className="topology-facts quality-facts"><span><TimerReset size={16} /><b>{services.data!.length}</b> critical services</span><span><ShieldCheck size={16} /><b>{policies.data!.length}</b> response policies</span><span><FlaskConical size={16} /><b>{exercised.length}</b> saved exercises</span><span><ClipboardCheck size={16} /><b>{unresolved.length}</b> open incidents</span></section>
    <section className="resilience-grid"><article className="data-panel"><header><div><span className="panel-label">Recovery objectives</span><h2>Critical services</h2></div></header><div className="resilience-list">{services.data!.map((service) => <div key={service.id}><b>{service.name}</b><span>Recovery target {service.recoveryTimeMinutes}m · MTD {service.maximumTolerableDowntimeMinutes}m</span></div>)}{!services.data!.length && <p className="empty-copy">Record critical services and recovery objectives to establish BCP/DR evidence.</p>}</div></article><article className="data-panel"><header><div><span className="panel-label">Human-run exercises</span><h2>Response simulations</h2></div></header><div className="resilience-list">{scenarios.data!.map((scenario) => <div key={scenario.id}><b>{scenario.options.length} modeled response options</b><span>{scenario.status.replaceAll("_", " ")} · {time(scenario.generatedAt)}</span></div>)}{!scenarios.data!.length && <p className="empty-copy">Run a policy-governed simulation to record an exercise; it never executes a response.</p>}</div></article></section>
    <section className="data-panel quality-limitations"><header><div><span className="panel-label">Readiness boundary</span><h2>Interpretation</h2></div></header><ul><li>Saved simulations model decisions; they do not prove recovery execution or operational restoration.</li><li>Open incidents are shown as planning context, not an automatic declaration of failed resilience.</li><li>Future expansion will add durable exercise plans, participant attestations, and recovery-test evidence.</li></ul></section>
  </>;
}
