import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { type FormEvent, useState } from "react";
import { FlaskConical, ShieldAlert } from "lucide-react";
import { api } from "../api";
import { ErrorState, Loading, PageHeading } from "../components/Ui";

export function SimulationPage() {
  const client = useQueryClient(); const analyses = useQuery({ queryKey: ["analyses"], queryFn: api.analyses }); const incidents = useQuery({ queryKey: ["incidents"], queryFn: api.incidents }); const assets = useQuery({ queryKey: ["assets"], queryFn: api.assets }); const [result, setResult] = useState<Awaited<ReturnType<typeof api.simulateResponse>>>();
  const simulate = useMutation({ mutationFn: api.simulateResponse, onSuccess: (scenario) => { setResult(scenario); client.invalidateQueries({ queryKey: ["responses"] }); } });
  const error = [analyses, incidents, assets].find((item) => item.error)?.error; if (analyses.isLoading || incidents.isLoading || assets.isLoading) return <Loading label="Loading real simulation inputs" />; if (error) return <ErrorState error={error} />;
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); simulate.mutate({ analysisId: String(data.get("analysisId")), incidentId: String(data.get("incidentId")), candidates: [{ title: String(data.get("title")), actionType: String(data.get("actionType")), targetAssetIds: [...data.getAll("assetIds")].map(String), targetDependencyIds: [], reversible: data.get("reversible") === "on", rollbackPlan: String(data.get("rollbackPlan")), rationale: String(data.get("rationale")) }] }); };
  return <><PageHeading eyebrow="Phase 22 / policy simulation" title="Response simulation builder" copy="Model the trade-offs of a proposed action against stored topology, services, policies, and incident evidence before a human decision is recorded." />
    <section className="simulation-boundary"><ShieldAlert size={18} /><span>This creates a decision-support scenario only. It cannot execute a control action.</span></section><form className="data-panel simulation-form" onSubmit={submit}><header><div><span className="panel-label">Operator-proposed candidate</span><h2>Compare a response option</h2></div><FlaskConical size={18} /></header><div className="config-body"><label>Risk analysis<select name="analysisId" required><option value="">Choose stored analysis</option>{analyses.data!.map((analysis) => <option key={analysis.id} value={analysis.id}>{analysis.id.slice(0, 8)} · {analysis.paths.length} paths</option>)}</select></label><label>Incident<select name="incidentId" required><option value="">Choose incident</option>{incidents.data!.filter((incident) => !["resolved", "closed"].includes(incident.status)).map((incident) => <option key={incident.id} value={incident.id}>{incident.reference} · {incident.title}</option>)}</select></label><label>Candidate title<input name="title" minLength={2} required placeholder="Isolate affected endpoint" /></label><label>Action type<select name="actionType"><option>isolate_asset</option><option>segment_connection</option><option>restrict_identity</option><option>disable_remote_access</option><option>block_indicator</option><option>shutdown_service</option></select></label><label>Target assets<select name="assetIds" multiple required size={Math.min(6, Math.max(2, assets.data!.length))}>{assets.data!.map((asset) => <option key={asset.id} value={asset.id}>{asset.name}</option>)}</select></label><label>Rationale<textarea name="rationale" rows={3} required placeholder="Why this option is relevant to the observed evidence." /></label><label className="check-label"><input name="reversible" type="checkbox" defaultChecked /> This action can be rolled back</label><label>Rollback plan<textarea name="rollbackPlan" rows={3} placeholder="Required for reversible actions." /></label>{simulate.error && <ErrorState error={simulate.error} />}{!analyses.data!.length && <p className="blocked-copy">Create an attack-path analysis before simulating a response.</p>}{!incidents.data!.some((incident) => !["resolved", "closed"].includes(incident.status)) && <p className="blocked-copy">Create an open incident before simulating a response.</p>}<button className="button button--primary" disabled={simulate.isPending || !analyses.data!.length || !incidents.data!.some((incident) => !["resolved", "closed"].includes(incident.status))}>{simulate.isPending ? "Simulating" : "Create governed scenario"}</button></div></form>{result && <section className="notice"><b>Scenario created:</b> {result.options.length} policy-evaluated option(s). Open the Decision Desk to record human approval or rejection.</section>
  }</>;
}
