import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CheckSquare, CircleAlert, PlayCircle } from "lucide-react";
import { api } from "../api";
import { ErrorState, Loading, PageHeading, Severity, time } from "../components/Ui";

export function TaskboardPage() {
  const client = useQueryClient(); const incidents = useQuery({ queryKey: ["incidents"], queryFn: api.incidents }); const update = useMutation({ mutationFn: ({ incidentId, taskId, status }: { incidentId: string; taskId: string; status: "todo" | "in_progress" | "blocked" | "done" }) => api.updateIncidentTask(incidentId, taskId, { status, comment: `Task state changed to ${status} from the Phase 18 human-runbook board.` }), onSuccess: () => client.invalidateQueries({ queryKey: ["incidents"] }) });
  if (incidents.isLoading) return <Loading label="Loading human runbook tasks" />; if (incidents.error) return <ErrorState error={incidents.error} />;
  const tasks = incidents.data!.flatMap((incident) => incident.tasks.map((task) => ({ incident, task }))).filter(({ incident }) => !["resolved", "closed"].includes(incident.status)).sort((a, b) => a.task.status === "done" ? 1 : b.task.status === "done" ? -1 : a.task.createdAt.localeCompare(b.task.createdAt));
  return <><PageHeading eyebrow="Phase 18 / human runbooks" title="Incident taskboard" copy="Human-owned operational tasks attached to durable incidents. Completion is always explicitly recorded by an authorized operator." />
    <section className="task-columns">{(["todo", "in_progress", "blocked", "done"] as const).map((status) => <section className="data-panel" key={status}><header><div><span className="panel-label">{status.replaceAll("_", " ")}</span><h2>{tasks.filter((item) => item.task.status === status).length} tasks</h2></div>{status === "blocked" ? <CircleAlert size={17} /> : status === "done" ? <CheckSquare size={17} /> : <PlayCircle size={17} />}</header><div className="task-stack">{tasks.filter((item) => item.task.status === status).map(({ incident, task }) => <article key={task.id}><div><Severity value={incident.severity} /><span>{incident.reference}</span></div><h3>{task.title}</h3><p>{task.description}</p><small>Created {time(task.createdAt)}</small>{task.status !== "done" && <footer>{task.status === "todo" && <button onClick={() => update.mutate({ incidentId: incident.id, taskId: task.id, status: "in_progress" })}>Start</button>}{task.status !== "blocked" && <button onClick={() => update.mutate({ incidentId: incident.id, taskId: task.id, status: "blocked" })}>Block</button>}<button onClick={() => update.mutate({ incidentId: incident.id, taskId: task.id, status: "done" })}>Mark done</button></footer>}</article>)}{!tasks.some((item) => item.task.status === status) && <p className="empty-copy">No {status.replaceAll("_", " ")} tasks.</p>}</div></section>)}</section>
  </>;
}
